trigger:
  branches:
    include:
      - main

stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: CmdLine@2
      displayName: 'Build and Run Unit Tests'
      inputs:
        script: mvn clean test 

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
        testResultsFormat: 'JUnit'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'target'
        ArtifactName: 'drop'
        publishLocation: 'Container'
